blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:post_slug>/', views.detail, name='detail'),
    path('<slug:post_slug>/results/', views.results, name='results'),
    path('<slug:post_slug>/submit/', views.submit, name='submit'),
]

polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:post_slug>/', views.detail, name='detail'),
    path('<slug:post_slug>/results/', views.results, name='results'),
    path('<slug:post_slug>/submit/', views.submit, name='submit')
]

project_main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
import datetime
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from autoslug import AutoSlugField

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=150)
    post = models.TextField()
    pub_date = models.DateTimeField('date_published')
    post_slug = AutoSlugField(populate_from='title', unique=True)

    def save(self, *args, **kwargs):
        """overwrites internal save() to automatically create a slug, if not provided"""
        if not self.post_slug:
            self.post_slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def post_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now()

class Question(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    pub_date = models.DateTimeField('date_published')
    question_slug = AutoSlugField(populate_from='title', unique=True)

    def save(self, *args, **kwargs):
        """overwrites internal save() to automatically create a slug, if not provided"""
        if not self.question_slug:
            self.question_slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=150)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class User(models.Model):
    like_rating = models.IntegerField(default=0)
    user_feedback = models.TextField()
    feedback_date = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from blog.models import Post, Question, Choice, User

# Create your views here.
def index(request):
    latest_posts_list = Post.objects.order_by('-pub_date')[:5]
    context = {
        'latest_posts_list': latest_posts_list
        }
    return render(request, 'blog/index.html', context)

def detail(request, post_slug):
    post = get_object_or_404(Post, post_slug=post_slug)
    question_list = Question.objects.all()
    for question in question_list:
        if post == question.post:
            question = question
            break
    context = {
        'post': post,
        'question': question
        }
    return render(request, 'blog/detail.html', context)

def submit(request, post_slug):
    mood_level = int(request.POST['mood_level'])
    user_info = User(like_rating=mood_level, user_feedback=request.POST['user_feedback'], feedback_date=timezone.now())
    user_info.save()
    post = get_object_or_404(Post, post_slug=post_slug)
    question_list = Question.objects.all()
    for question in question_list:
        if post == question.post:
            question = question
    try:
        # get submitted data from DB
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # redisplay detail page for invalid submissions
        context = {
            'question': question,
            'error_message': "You didn't select a choice."
            }
        return render(request, 'blog/detail.html', context)
    else:
        # increment vote tally for selected choice and save
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('blog:results', args=(post.post_slug,)))

def results(request, post_slug):
    post = get_object_or_404(Post, post_slug=post_slug)
    question_list = Question.objects.all()
    for question in question_list:
        if post == question.post:
            question = question
    user_info = User.objects.latest('feedback_date')
    context = {
        'post': post,
        'question': question,
        'user_info': user_info,
        }
    return render(request, 'blog/results.html', context)

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from polls.models import Post, Question, Choice, User

# Create your views here.
def index(request):
    latest_posts_list = Post.objects.order_by('-pub_date')[:5]
    context = {
        'latest_posts_list': latest_posts_list
        }
    return render(request, 'polls/index.html', context)

def detail(request, post_slug):
    post = get_object_or_404(Post, post_slug=post_slug)
    question_list = Question.objects.all()
    for question in question_list:
        if post == question.post:
            question = question
    context = {
        'post': post,
        'question': question
        }
    return render(request, 'polls/detail.html', context)

def submit(request, post_slug):
    mood_level = int(request.POST['mood_level'])
    user_info = User(like_rating=mood_level, user_feedback=request.POST['user_feedback'], feedback_date=timezone.now())
    user_info.save()
    post = get_object_or_404(Post, post_slug=post_slug)
    question_list = Question.objects.all()
    for question in question_list:
        if post == question.post:
            question = question
    try:
        # get submitted data from DB
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # redisplay detail page for invalid submissions
        context = {
            'question': question,
            'error_message': "You didn't select a choice."
            }
        return render(request, 'polls/detail.html', context)
    else:
        # increment vote tally for selected choice and save
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(post.post_slug,)))

def results(request, post_slug):
    post = get_object_or_404(Post, post_slug=post_slug)
    question_list = Question.objects.all()
    for question in question_list:
        if post == question.post:
            question = question
    user_info = User.objects.latest('feedback_date')
    context = {
        'post': post,
        'question': question,
        'user_info': user_info,
        }
    return render(request, 'polls/results.html', context)

blog/templates/blog/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>
<body>

{% block content %}

{% endblock content %}
    
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}

{% load static  %}

<div class="card mb-3">
    <img src="{% static 'blog/codingnomads_logo.png' %}" class="card-img-top" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.post }}</p>
        <p class="card-text"><small class="text-muted">{{ post.pub_date }}</small></p>
    </div>
</div>

<br>

<h5>Question: {{ question.title }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'blog:submit' post.post_slug %}" method="post">
    {% csrf_token %}
    <div>
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
        {% endfor %}
    </div>

    <br>

    <div>
        <label for="customRange3" class="form-label">
            <h5>Like the post?</h2>
            <p class='text-muted'>Give us a rating: </p>
        </label>
        <input type="range" name="mood_level" min="1" max="10" step="1">
        <br>
        <textarea name="user_feedback" placeholder="The reason for your above choice?" cols="70" rows="7"></textarea>
    </div>
    <br>
    <input type="submit" value="Submit">
</form>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">
            <h3>Django Learn</h3>
            <small class="text-muted">
                <h4>Programming with Python & Django</h4>
            </small>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="https://docs.python.org/3/">Python Docs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://docs.djangoproject.com/en/3.2/">Django Docs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://codingnomads.co/">CodingNomads</a>
            </li>
        </ul>
    </div>
</nav>

<br>


{% if latest_posts_list %}
    
<ul>
    
    {% for post in latest_posts_list %}
        
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ post.pub_date }}</h6>
            <p class="card-text">{{ post.post|truncatechars:30 }}</p>
            <a href="{% url 'blog:detail' post.post_slug %}">Link to post</a>
        </div>
    </div>
    <br>

    {% endfor %}
        
</ul>

{% endif %}

{% endblock content%}

blog/templates/blog/results.html
{% extends 'blog/base.html' %}

{% block content %}

<body>

    <div class="card" style="width: 25rem;">
        <div class="card-body">
          <h5 class="card-title">{{ post.title }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ question.title }}</h6>
          
          {% for choice in question.choice_set.all %}
              
          <li class="card-text">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>

          {% endfor %}
              
          
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>

    <br>

    <h1>Submitted Feedback:</h1>
    <li><b>Like Rating: </b>{{ user_info.like_rating }}</li>
    <li><b>Date: </b>{{ user_info.feedback_date }}</li>
    <li><b>Feedback: </b>{{ user_info.user_feedback }}</li>

    <br>
    <a href="{% url 'blog:index' %}">Back to the index page?</a>
</body>

{% endblock content %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}

{% load static  %}

<div class="card mb-3">
    <img src="{% static 'polls/codingnomads_logo.png' %}" class="card-img-top" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.post }}</p>
        <p class="card-text"><small class="text-muted">{{ post.pub_date }}</small></p>
    </div>
</div>

<br>

<h5>Question: {{ question.title }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:submit' post.post_slug %}" method="post">
    {% csrf_token %}
    <div>
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
        {% endfor %}
    </div>

    <br>

    <div>
        <label for="customRange3" class="form-label">
            <h5>Like the post?</h2>
            <p class='text-muted'>Give us a rating: left = poor, right = good: </p>
        </label>
        <input type="range" name="mood_level" min="1" max="10" step="1">
        <br>
        <textarea name="user_feedback" placeholder="The reason for your above choice?" cols="70" rows="7"></textarea>
    </div>
    <br>
    <input type="submit" value="Submit">
</form>

{% endblock content %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">
            <h3>Django Learn</h3>
            <small class="text-muted">
                <h4>Programming with Python & Django</h4>
            </small>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="https://docs.python.org/3/">Python Docs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://docs.djangoproject.com/en/3.2/">Django Docs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://codingnomads.co/">CodingNomads</a>
            </li>
        </ul>
    </div>
</nav>

<br>


{% if latest_posts_list %}
    
<ul>
    
    {% for post in latest_posts_list %}
        
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ post.pub_date }}</h6>
            <p class="card-text">{{ post.post|truncatechars:30 }}</p>
            <a href="{% url 'polls:detail' post.post_slug %}">Link to post</a>
        </div>
    </div>
    <br>

    {% endfor %}
        
</ul>

{% endif %}

{% endblock content%}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}

<body>

    <div class="card" style="width: 25rem;">
        <div class="card-body">
          <h5 class="card-title">{{ post.title }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ question.title }}</h6>
          
          {% for choice in question.choice_set.all %}
              
          <li class="card-text">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>

          {% endfor %}
              
          
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>

    <br>

    <h1>Submitted Feedback:</h1>
    <li><b>Like Rating: </b>{{ user_info.like_rating }}</li>
    <li><b>Date: </b>{{ user_info.feedback_date }}</li>
    <li><b>Feedback: </b>{{ user_info.user_feedback }}</li>

    <br>
    <a href="{% url 'polls:index' %}">Back to the index page?</a>
</body>

{% endblock content %}